import { dbQuery, dbGet } from '../db/connection.js';

/**
 * Agni Guardian - Market Intelligence & Profit Hub
 * Calculates Mark-to-Market (MTM) valuation and business forecasts.
 */
export const GuardianService = {
  /**
   * Calculates the current total valuation of all showroom stock.
   */
  async getMTMValuation() {
    try {
      // Get current gold rates
      const rate = await dbGet(`SELECT gold_22k, gold_24k, silver_fine FROM rates ORDER BY created_at DESC LIMIT 1`);
      
      // Aggregate stock by purity
      const stockAggregation = await dbQuery(`
        SELECT p.purity, SUM(s.net_weight) as total_weight
        FROM stock s
        JOIN products p ON s.product_id = p.id
        WHERE s.status = 'AVAILABLE'
        GROUP BY p.purity
      `);

      let totalValue = 0;
      let totalWeight = 0;

      stockAggregation.forEach((group: any) => {
        const weight = group.total_weight || 0;
        totalWeight += weight;
        
        if (group.purity.includes('22')) {
          totalValue += weight * rate.gold_22k;
        } else if (group.purity.includes('24')) {
          totalValue += weight * rate.gold_24k;
        } else if (group.purity.includes('Silver')) {
          totalValue += weight * rate.silver_fine;
        } else {
          // Fallback to 22k for mixed or unknown
          totalValue += weight * rate.gold_22k;
        }
      });

      return {
        totalValue,
        totalWeight,
        timestamp: new Date(),
        gold_22k_rate: rate.gold_22k
      };
    } catch (err) {
      console.error('MTM Calculation Error', err);
      throw err;
    }
  },

  /**
   * Generates the "Business Pulse" Intelligence Report for the owner.
   */
  async generateExecutiveReport() {
    const mtm = await this.getMTMValuation();
    
    // Get yesterday's sales
    const yesterday = new Date();
    yesterday.setDate(yesterday.getDate() - 1);
    const dateStr = yesterday.toISOString().split('T')[0];

    const salesStats = await dbGet(`
      SELECT SUM(net_amount) as total_revenue, COUNT(*) as txn_count
      FROM billing
      WHERE sale_date LIKE ?
    `, [`${dateStr}%`]);

    return `
      <h2>🏛️ Agni Jewellery Executive Intelligence</h2>
      <p><em>Market Sentiment & Enterprise Valuation Report</em></p>
      <hr />
      
      <h3>📈 Showroom Real-Time Valuation (MTM)</h3>
      <p><strong>Total Showroom Net Weight:</strong> ${mtm.totalWeight.toFixed(3)}g</p>
      <p><strong>Current Inventory Market Value:</strong> ₹${Math.round(mtm.totalValue).toLocaleString('en-IN')}</p>
      <p><strong>Basis Gold Rate (22k):</strong> ₹${mtm.gold_22k_rate}/g</p>
      
      <h3>💰 Previous Day Performance (${dateStr})</h3>
      <p><strong>Total Revenue generated:</strong> ₹${Math.round(salesStats.total_revenue || 0).toLocaleString('en-IN')}</p>
      <p><strong>Total Transactions:</strong> ${salesStats.txn_count || 0}</p>
      
      <hr />
      <p style="color: #666; font-size: 0.8em;">Generated by Agni Guardian AI v2.0 - Total Data Encryption Active.</p>
    `;
  }
};
